/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_rosjava_tutorial_native_node_PsmNativeNode */

#ifndef _Included_org_ros_rosjava_tutorial_native_node_PsmNativeNode
#define _Included_org_ros_rosjava_tutorial_native_node_PsmNativeNode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ros_rosjava_tutorial_native_node_PsmNativeNode_SUCCESS
#define org_ros_rosjava_tutorial_native_node_PsmNativeNode_SUCCESS 0L
/*
 * Class:     org_ros_rosjava_tutorial_native_node_PsmNativeNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_PsmNativeNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_PsmNativeNode
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_PsmNativeNode_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
